simple-build: adding windows compat

diff --git a/simple-build b/simple-build
--- a/simple-build
+++ b/simple-build
@@ -8,7 +8,85 @@ YELLOW="\e[93m"
 scriptpath="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 build_path="./build"
 log_path="./log-sb"
+OSTYPE=$(uname)
+cmake_subproject_list=
 
+getOS()
+{
+	local _retval="$1"
+	local result=""
+	case "$OSTYPE" in
+		msys)
+			result="win"
+			;;
+		cygwin)
+			result="win"
+			;;
+		darwin*)
+			result="mac"
+			;;
+		Linux*) 
+			result="linux"
+			;;
+		linux-gnu*)
+			# We have to check for WSL
+			if [[ `uname -r` == *"Microsoft"* ]]; then
+				result="win"
+			else
+				result="linux"
+			fi
+			;;
+		*)
+			echo "ERROR: Unknown OSTYPE: $OSTYPE"
+			exit 127
+			;;
+	esac
+
+	eval $_retval="'${result}'"
+}
+
+# Returns 0 if running OS is windows
+check_is_windows()
+{
+	local osName
+	getOS osName
+
+	if [ "$osName" = "win" ]; then
+		return 0
+	fi
+
+	return 0
+}	
+
+# Returns 0 if running OS is mac
+check_is_mac()
+{
+	local osName
+	getOS osName
+	if [[ $osName = "mac" ]]; then
+		return 0
+	fi
+	return 1
+}
+
+# Returns 0 if running OS is linux
+check_is_linux()
+{
+	local osName
+	getOS osName
+	if [[ $osName = "linux" ]]; then
+		return 1
+	fi
+	return 1
+}
+
+check_os_compatible()
+{
+	if [ is_mac -eq 0 ]; then
+		printf "${RED}Mac was not tested ${RESET}\n"
+		exit 255
+	fi
+}
 
 tarball_retrieve()
 {
